### ISSUE TITLE
Plugin fails when multiple periods in the file name using gulp (v4.0)

### ISSUE THREAD

**Issue by jpduckwo** [jruchaud/gulp-platform-file#3]
Hi, I'm really keen to use this plugin but I'm getting a problem where if a file has multiple periods it just gets failed to be included by the filter. 

e.g.
If you have 'app.config.js' the filter will just leave the file out completely, where as 'appConfig.js' would be included.

Also if you have 'app.config.js' and 'app.config-ios.js' and run gulp  --ios the resulting file is 'app-config.js'! Which is totally wrong...

Have you any idea how this can be solved? I'm guessing it might be cause by splitting the filename on period and assuming there is only going to be one.

Many thanks!

**Comment by jruchaud** [comment]
I have done the modification to support the period in file name. Could you check in your side, before I make a new version ?

**Comment by jruchaud** [comment]
I have simplify the code, so you can retry.

**Comment by jpduckwo** [comment]
Hey @jruchaud, I've tested and it is working to fix the bug mentioned! Thank you.

However I came across another bug that it doesn't work for files with no extension. Should I raise a new issue for this?

With files named:
test
test-cordova

When I run through the plugin I only end up with the 'test' file which is good, but if I specify the platform cordova then I still get the contents of 'test' instead of 'test-cordova' in the output file.

**Comment by jruchaud** [comment]
Yes you can make an issue. I try to fix today the problem.

**Comment by jpduckwo** [comment]
Here we go [#6](https://github.com/jruchaud/gulp-platform-file/issues/6)

**Comment by jruchaud** [comment]
Thanks
