### ISSUE TITLE
Feature request: allow platform selection by function argument rather than command line

### ISSUE THREAD

**Issue by jpduckwo** [jruchaud/gulp-platform-file#5]
Currently it seems the only way to target the platform you want to filter on is to use command line flags. e.g gulp --ios

However it would be really awesome to be able set the target platform as an argument to the function when run.

This would then let me create gulp tasks that target different platforms and make the plugin more flexible and also allow you to build multiple different platforms in one gulp call.

e.g. for gulp

```
var platformify = require("gulp-platform-file")

gulp.task("default-ios", function() {
    gulp.src("workspace/**")
        .pipe(
            // This would be the same as running gulp --ios
            platformify().filter({
                dimensions: ['ios', 'android'],
                activeDimensions: ['ios'],
            })
        )
        .pipe(gulp.dest("build/"));
});

```

**Comment by jruchaud** [comment]
I will check, but for me you can force the dimension before call platformify like is:

    var gutil = require("gulp-util");
    gutil.env.ios = true // or null

**Comment by jpduckwo** [comment]
ok cool that will probably work for me thanks

**Comment by jpduckwo** [comment]
It worked thanks
