### ISSUE TITLE
Platform doesn't handle files with no extension

### ISSUE THREAD

**Issue by jpduckwo** [jruchaud/gulp-platform-file#6]
When using trying platformify files with no extension, the plugin recognises the files as platform specific but doesn't use the right version of the file for the selected platform. It always uses the non platform file.

e.g.
Files:

```
manifest
manifest-ios
manifest-android
```

Running gulp --ios the outputted file 'manifest' should contain the contents of 'manifest-ios' but  contains the contents of 'manifest'.

**Comment by jruchaud** [comment]
Fixed.
Could you test in your side before I made a version ?

**Comment by jpduckwo** [comment]
Hey @jruchaud, I've tested and it works, great stuff thanks!

**Comment by jruchaud** [comment]
A new version 1.8.2 is available.
